# Generated by Django 5.1.7 on 2025-03-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_alter_room_slug'),
        ('tickets', '0007_remove_ticket_acoes_ticket_historico_acoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ticket',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='tickets.ticket'),
            preserve_default=False,
        ),
    ]
