# Generated by Django 5.1.7 on 2025-03-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_room_ticket'),
        ('tickets', '0007_remove_ticket_acoes_ticket_historico_acoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='tickets.ticket'),
        ),
    ]
