# Generated by Django 5.1.7 on 2025-03-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_incidente', models.CharField(max_length=50, verbose_name='Incidente')),
                ('codigo_sx', models.CharField(blank=True, default='', max_length=50, verbose_name='SX')),
                ('recurso', models.CharField(max_length=50, verbose_name='Recurso')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('problema_apresentado', models.TextField(verbose_name='Problema Apresentado')),
                ('acoes', models.TextField(verbose_name='Ações')),
                ('solucao_contorno', models.TextField(verbose_name='Solução de Contorno')),
                ('causa_raiz', models.TextField(verbose_name='Causa Raiz')),
                ('previsao', models.IntegerField(blank=True, null=True)),
                ('link_alerta', models.URLField(blank=True, null=True, verbose_name='Alerta Dynatrace')),
                ('link_itsm', models.URLField(blank=True, null=True, verbose_name='Link do Incidente ITSM')),
                ('grupo_suporte', models.CharField(choices=[('COI - Grupo de Operações Integradas', 'COI - Grupo de Operações Integradas'), ('COI - Gestão de Problemas', 'COI - Gestão de Problemas'), ('Operações IBM', 'Operações IBM')], default='', max_length=100, verbose_name='Grupo de Suporte')),
                ('analista', models.CharField(choices=[('Leandro Fratel', 'Leandro Fratel'), ('Heráclito Teixeira', 'Heráclito Teixeira'), ('Camilla Gama', 'Camilla Gama')], default='Não Atribuido', max_length=100, verbose_name='Analista')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado'), ('Resolvido', 'Resolvido'), ('Em Andamento', 'Em Andamento'), ('Designado', 'Designado'), ('Em Análise', 'Em Análise'), ('Sala de Crise', 'Sala de Crise')], default='Aberto', max_length=50, verbose_name='Status')),
                ('criticidade', models.CharField(choices=[('Crítico', 'Crítico'), ('Muito Crítico', 'Muito Crítico'), ('Hiper Crítico', 'Hiper Crítico')], default='Crítico', max_length=50, verbose_name='Criticidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/files/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/images/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.ticket')),
            ],
        ),
    ]
