# Generated by Django 5.1.7 on 2025-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='analista',
            field=models.CharField(blank=True, default='Não Atribuido', max_length=100, null=True, verbose_name='Analista'),
        ),
    ]
