# Generated by Django 5.1.7 on 2025-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='previsao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Previsão em minutos'),
        ),
    ]
