# Generated by Django 5.1.7 on 2025-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_analista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problema_apresentado',
            field=models.CharField(max_length=200, verbose_name='Problema Apresentado'),
        ),
    ]
