# Generated by Django 5.1.7 on 2025-03-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_previsao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketFile',
        ),
    ]
