# Generated by Django 5.1.7 on 2025-03-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_delete_ticketfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problema_apresentado',
            field=models.CharField(max_length=50, verbose_name='Problema Apresentado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recurso',
            field=models.CharField(choices=[('AGENDAMENTO UNIVERSAL - AGENDA SP', 'AGENDAMENTO UNIVERSAL - AGENDA SP'), ('APLICAÇÕES MOBILE', 'APLICAÇÕES MOBILE'), ('BALCÃO ÚNICO', 'BALCÃO ÚNICO'), ('CNH', 'CNH'), ('CRV', 'CRV'), ('DELEGACIA ELETRÔNICA', 'DELEGACIA ELETRÔNICA'), ('DETECTA', 'DETECTA'), ('GEDAVE', 'GEDAVE'), ('INFRAESTRUTURA DE VIRTUALIZACAO E STORAGE - SEDE', 'INFRAESTRUTURA DE VIRTUALIZACAO E STORAGE - SEDE'), ('INFRAESTRUTURA ELETRICA E AR CONDICIONADO - SEDE', 'INFRAESTRUTURA ELETRICA E AR CONDICIONADO - SEDE'), ('INQUÉRITO ELETRÔNICO', 'INQUÉRITO ELETRÔNICO'), ('IPVA ONLINE', 'IPVA ONLINE'), ('ITSM', 'ITSM'), ('MAINFRAME IBM', 'MAINFRAME IBM'), ('PLATAFORMA REDE SP.GOV.BR', 'PLATAFORMA REDE SP.GOV.BR'), ('PORTAL POUPATEMPO', 'PORTAL POUPATEMPO'), ('POUPAFILA CENTRALIZADO', 'POUPAFILA CENTRALIZADO'), ('POUPATEMPO - ENERGIA ELÉTRICA', 'POUPATEMPO - ENERGIA ELÉTRICA'), ('POUPATEMPO - LINK INTRAGOV', 'POUPATEMPO - LINK INTRAGOV'), ('PROVA ELETRÔNICA', 'PROVA ELETRÔNICA'), ('S4SP', 'S4SP'), ('SEI', 'SEI'), ('SIM', 'SIM'), ('VALID - IIRGD', 'VALID - IIRGD'), ('TOTEM', 'TOTEM')], max_length=50, verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='responsavel',
            field=models.CharField(max_length=100, verbose_name='Responsável'),
        ),
    ]
