# Generated by Django 5.1.7 on 2025-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_problema_apresentado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='codigo_incidente',
            field=models.CharField(max_length=50, unique=True, verbose_name='Incidente'),
        ),
    ]
