# Generated by Django 5.1.7 on 2025-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_codigo_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='analista',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Analista'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='criticidade',
            field=models.CharField(editable=False, max_length=50, verbose_name='Criticidade'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='grupo_suporte',
            field=models.CharField(choices=[('COI - Grupo de Operações Integradas', 'COI - Grupo de Operações Integradas'), ('COI - Gestão de Problemas', 'COI - Gestão de Problemas')], max_length=100, verbose_name='Grupo de Suporte'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='link_alerta',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Alerta Dynatrace'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='link_itsm',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link do Incidente ITSM'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Fechado', 'Fechado'), ('Resolvido', 'Resolvido'), ('Em Análise', 'Em Análise')], default='Aberto', max_length=50, verbose_name='Status'),
        ),
    ]
