# Generated by Django 5.1.7 on 2025-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_problema_apresentado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='criticidade',
            field=models.CharField(choices='', default='Crítico', editable=False, max_length=50, verbose_name='Criticidade'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recurso',
            field=models.CharField(choices=[('Balcão Único', 'Balcão Único'), ('Central de Transplantes', 'Central de Transplantes'), ('CNH', 'CNH'), ('CRV', 'CRV'), ('Plataforma REDE SP.GOV.BR', 'Plataforma REDE SP.GOV.BR'), ('Portal Detran', 'Portal Detran'), ('Portal Poupatempo', 'Portal Poupatempo'), ('Prova Eletrônica', 'Prova Eletrônica'), ('SEI', 'SEI'), ('TOTEM', 'TOTEM'), ('Agendamento Universal - Agenda SP', 'Agendamento Universal - Agenda SP'), ('CAR - Cadastro de Atendimento e Relacionamento', 'CAR - Cadastro de Atendimento e Relacionamento'), ('Delegacia Eletrônica', 'Delegacia Eletrônica'), ('e-Vistoria', 'e-Vistoria'), ('Multas DER', 'Multas DER'), ('Poupafila Centralizado', 'Poupafila Centralizado'), ('SIM', 'SIM'), ('SPJ', 'SPJ'), ('Aplicações Mobile', 'Aplicações Mobile'), ('Detecta', 'Detecta'), ('Inquérito Eletrônico', 'Inquérito Eletrônico'), ('Ipva Online', 'Ipva Online'), ('Rede Palácio do Governo', 'Rede Palácio do Governo'), ('S4SP', 'S4SP'), ('Sistema Alpha', 'Sistema Alpha'), ('Valid - IIRGD', 'Valid - IIRGD')], max_length=50, verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='responsavel',
            field=models.CharField(editable=False, max_length=100, verbose_name='Responsável'),
        ),
    ]
