# Generated by Django 5.1.7 on 2025-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_criticidade_alter_ticket_recurso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='causa_raiz',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='acoes',
            field=models.TextField(blank=True, verbose_name='Histórico de Ações'),
        ),
    ]
