# Generated by Django 5.1.7 on 2025-04-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_analista_alter_ticket_criticidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='grupo_suporte',
            field=models.CharField(choices=[('Grupo A', 'Grupo A'), ('Grupo B', 'Grupo B')], max_length=100, verbose_name='Grupo de Suporte'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='link_alerta',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link alerta Dynatrace'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recurso',
            field=models.CharField(choices=[('Alfa', 'Alfa'), ('Beta', 'Beta'), ('Gama', 'Gama'), ('Delta', 'Delta'), ('Epsilon', 'Epsilon'), ('Zeta', 'Zeta'), ('Eta', 'Eta'), ('Teta', 'Teta'), ('Iota', 'Iota')], max_length=50, verbose_name='Recurso'),
        ),
    ]
