# Generated by Django 5.1.7 on 2025-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_causa_raiz_alter_ticket_acoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='acoes',
        ),
        migrations.AddField(
            model_name='ticket',
            name='historico_acoes',
            field=models.TextField(blank=True, editable=False, verbose_name='Histórico de Ações'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solucao_contorno',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Solução de Contorno'),
        ),
    ]
